//Test Script

/*

integer num = 27;
integer remainder  = Math.mod(num, 4);
system.debug (remainder);
}
*/
PLACEHOLDER
public class CustomException extends Exception{}
try{
    
    System.assertequals(3, remainder);

} catch(Exception exc){
    throw new CustomException('there is a error '+exc.getMessage());
}
